default: &default
  adapter: postgresql
  encoding: unicode
  user: charty
  pasword: 123
  pool: 25
development:
  <<: *default
  database: congrats_development
test:
  <<: *default
  database: congrats_test
staging:
  <<: *default
  database: congrats_staging
production:
  <<: *default
  database: congrats_production
